version: 2.1
jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello."
  trouble:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble"
  workflows:
    version: 2.1
    hello_trouble:
      jobs:
        - hello
        - trouble
