version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
  useless:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo 'hello!'
workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - useless
      - test:
          requires:
            - useless
